#****************************************************************************
#
#    Copyright (C) 2025 David Latham
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
#    USA
#
# https://github.com/6502-retro/6502-retro-os
#
#****************************************************************************

TOP=.

include Make.default
-include Make.local

.PHONY: all clean os applications

all:: os applications

os:
	$(MAKE) -f Makefile.os

applications:
	$(MAKE) -C apps/lib
	$(MAKE) -C apps

clean:: clean-os clean-apps clean-sdcard-img

clean-os:
	$(MAKE) -f Makefile.os clean

clean-apps:
	$(MAKE) -C apps clean

clean-sdcard-img:
	rm -fv $(TOP)/py_sfs_v2/6502-retro-sdcard.img

BUILD=build
# only burn the OS image part of the sdcard image into the physical sdcard.
# Use when the OS is updated, but you don't want to remove all your drives and files.
burn-os: sdcard
	sudo dd if=$(BUILD)/rom.raw seek=1 bs=512 count=16 of=$(SDDEVICE) conv=fsync

# replace the whole SDCard image and all drives with whatever is on the sdcard image.
# Assumes name of sdcard image is the one generated by `make sdcard`
burn: sdcard
	sudo dd if=py_sfs_v2/6502-retro-sdcard.img bs=512 of=$(SDDEVICE) conv=fsync

sdcard: os applications
	cd $(TOP)/py_sfs_v2 && ./make_sdcard.sh && cd $(TOP)

world: clean all

