; vim: ft=asm_ca65
dispatch        = $200
bios_cboot      = $203
bios_wboot      = $206
bios_conout     = $209
bios_conin      = $20c
bios_const      = $20f
bios_puts       = $212
bios_prbyte     = $215

bios_setdma     = $218
bios_setlba     = $21b
bios_sdread     = $21e
bios_sdwrite    = $221

sn_beep         = $224
sn_start        = $227
sn_silence      = $22a
sn_stop         = $22d
sn_send         = $230
led_on          = $233
led_off         = $236
get_button      = $239

